// Code generated by go generate; DO NOT EDIT.
package infrastructure

const CREATE_REPOSITORY = `import groovy.json.JsonSlurper
import org.sonatype.nexus.repository.manager.RepositoryManager
import java.util.*

class Repository {
  Map<String, Map<String, Object>> properties = new HashMap<String, Map<String, Object>>()
}

if (args != "") {
  def rep = convertJsonFileToRepo(args)
  def output = createRepository(rep)

  return output
}

def convertJsonFileToRepo(String jsonData) {
  def inputJson = new JsonSlurper().parseText(jsonData)
  Repository repo = new Repository()

  inputJson.each {
    repo.properties.put(it.key, it.value)
  }

  return repo
}

def createRepository(Repository repo) {
  def conf = createConfiguration(repo)

  try {
    repository.createRepository(conf)
  }
  catch (Exception e) {
    if (e.getMessage().contains("Failed to initialize facets")) {
      return new RuntimeException("Could not create repository. Does it already exist? Please check the logs. " + e.toString(), e)
    }
    return e
  }

  return null
}

def createConfiguration(Repository repo) {
  def name = getName(repo)
  def recipeName = getRecipeName(repo)
  def online = getOnline(repo)
  Map<String, Object> attributes = repo.properties.get("attributes")

  def repoManager = container.lookup(RepositoryManager.class.name)
  def conf = repoManager.newConfiguration()
  conf.setRepositoryName(name)
  conf.setRecipeName(recipeName)
  conf.setOnline(online)
  conf.setAttributes(attributes)

  return conf
}


def getName(Repository repo) {
  String name = repo.getProperties().get("repositoryName")
  return name
}

def getRecipeName(Repository repo) {
  String recipeName = repo.getProperties().get("recipeName")
  return recipeName
}

def getOnline(Repository repo) {
  String online = repo.getProperties().get("online")
  return online.toBoolean()
}
`
const DELETE_REPOSITORY = `def deleteRepository(String name) {

  try {
    repository.getRepositoryManager().delete(name)
  }
  catch (Exception e){
    return e
  }
  return null
}

if (args != "") {

  def output = deleteRepository(args)

  return output
}

`
const MODIFY_REPOSITORY = `import groovy.json.JsonSlurper
import org.sonatype.nexus.repository.Repository

class RepositoryMap {
  Map<String, Map<String, Object>> properties = new HashMap<String, Object>()
}

if (args != "") {
  RepositoryMap repoMap = convertJsonFileToRepoMap(args)
  Repository repo = getRepositoryFromJsonData(repoMap)
  def conf = repo.getConfiguration().copy()
  def attributes = repoMap.properties.get("attributes")
  conf.setAttributes(attributes)

  try {
    repository.getRepositoryManager().update(conf)
  }
  catch (Exception e) {
    return e
  }

  return null
}

Repository getRepositoryFromJsonData(RepositoryMap repoMap){
  return repository.getRepositoryManager().get(repoMap.properties.get("repositoryName"))
}

RepositoryMap convertJsonFileToRepoMap(String jsonData) {
  def inputJson = new JsonSlurper().parseText(jsonData)
  RepositoryMap repo = new RepositoryMap()
  inputJson.each {
    repo.properties.put(it.key, it.value)
  }

  return repo
}
`
const READ_REPOSITORY = `import groovy.json.JsonOutput
import groovy.json.JsonSlurper

if (args != "") {

  def configurationMap = retrieveRepositoryConfiguration(args)
  return JsonOutput.toJson(configurationMap)
}

def retrieveRepositoryConfiguration(String repositoryId) {
  def result = new HashMap<String, String>()
  def repository = repository.getRepositoryManager().get(repositoryId)
  try{
    //add actual configuration of repository
    result.put ("attributes", repository.getConfiguration().getAttributes())
  }
  catch (Exception e){
    if (e instanceof NullPointerException){
      return "404: no repository found"
    }
    return e
  }
  //add what Nexus calls meta-data
  result.put ("id", repository.getName())
  result.put ("format", repository.getFormat().value)
  result.put ("type", repository.getType().getValue())

  return result
}

`
